name: mp2pp autograding
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: cs340-illinois/sp24_cs340_.release
        ref: mp2pp
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp2pp
        dst_path: mp2pp
        copy: '.github/classroom : .github/classroom, Makefile : Makefile, tests : tests'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp2pp/.github/classroom : mp2pp/.github/classroom, release/mp2pp/Makefile : mp2pp/Makefile, release/mp2pp/tests : mp2pp/tests'
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: mp2pp/
        test_suite: autograding
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
  valgrind:
    name: valgrind
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: cs340-illinois/sp24_cs340_.release
        ref: mp2pp
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp2pp
        dst_path: mp2pp
        copy: '.github/classroom : .github/classroom, Makefile : Makefile, tests : tests'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp2pp/.github/classroom : mp2pp/.github/classroom, release/mp2pp/Makefile : mp2pp/Makefile, release/mp2pp/tests : mp2pp/tests'
    - name: Install valgrind
      run: sudo apt update -y && sudo apt install -y valgrind
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: mp2pp/
        test_suite: valgrind
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
    needs:
    - autograding
