name: mp5 autograding
'on':
  workflow_dispatch: {}
jobs:
  coderules:
    name: coderules
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: cs340-illinois/sp24_cs340_.release
        ref: mp5
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp5
        dst_path: mp5
        copy: '.github/classroom : .github/classroom, test_coding_rules.py: test_coding_rules.py, test_part_1.py : test_part_1.py, test_part_2.py : test_part_2.py, test_part_3.py : test_part_3.py, test_part_4.py : test_part_4.py, test_provided_files.py : test_provided_files.py, degree.py : degree.py, hedgehog-rat.py : hedgehog-rat.py, ping-pong.py : ping-pong.py, gacha.py : gacha.py, hedgehog-simple.py : hedgehog-simple.py, ping-pong-transaction.py : ping-pong-transaction.py'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp5/.github/classroom : mp5/.github/classroom, release/mp5/test_coding_rules.py : mp5/test_coding_rules.py, release/mp5/test_part_1.py : mp5/test_part_1.py, release/mp5/test_part_2.py : mp5/test_part_2.py, release/mp5/test_part_3.py : mp5/test_part_3.py, release/mp5/test_part_4.py : mp5/test_part_4.py, release/mp5/test_provided_files.py : mp5/test_provided_files.py, release/mp5/degree.py : mp5/degree.py, release/mp5/hedgehog-rat.py : mp5/hedgehog-rat.py, release/mp5/ping-pong.py : mp5/ping-pong.py, release/mp5/gacha.py : mp5/gacha.py, release/mp5/hedgehog-simple.py : mp5/hedgehog-simple.py, release/mp5/ping-pong-transaction.py : mp5/ping-pong-transaction.py'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: pip install -r mp5/requirements.txt
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: mp5/
        test_suite: coderules
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: coderules
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: cs340-illinois/sp24_cs340_.release
        ref: mp5
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp5
        dst_path: mp5
        copy: '.github/classroom : .github/classroom, test_coding_rules.py: test_coding_rules.py, test_part_1.py : test_part_1.py, test_part_2.py : test_part_2.py, test_part_3.py : test_part_3.py, test_part_4.py : test_part_4.py, test_provided_files.py : test_provided_files.py, degree.py : degree.py, hedgehog-rat.py : hedgehog-rat.py, ping-pong.py : ping-pong.py, gacha.py : gacha.py, hedgehog-simple.py : hedgehog-simple.py, ping-pong-transaction.py : ping-pong-transaction.py'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp5/.github/classroom : mp5/.github/classroom, release/mp5/test_coding_rules.py : mp5/test_coding_rules.py, release/mp5/test_part_1.py : mp5/test_part_1.py, release/mp5/test_part_2.py : mp5/test_part_2.py, release/mp5/test_part_3.py : mp5/test_part_3.py, release/mp5/test_part_4.py : mp5/test_part_4.py, release/mp5/test_provided_files.py : mp5/test_provided_files.py, release/mp5/degree.py : mp5/degree.py, release/mp5/hedgehog-rat.py : mp5/hedgehog-rat.py, release/mp5/ping-pong.py : mp5/ping-pong.py, release/mp5/gacha.py : mp5/gacha.py, release/mp5/hedgehog-simple.py : mp5/hedgehog-simple.py, release/mp5/ping-pong-transaction.py : mp5/ping-pong-transaction.py'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: pip install -r mp5/requirements.txt
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: mp5/
        test_suite: autograding
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
